#!/bin/bash
echo "🎉 Script de teste funcionando!"
echo "📍 Executando em: $(pwd)"
echo "⏰ Data/hora: $(date)"
echo ""
echo "✅ VALIDAÇÃO CONFIRMADA!"
echo "✅ Posso criar pastas: OK"
echo "✅ Posso criar arquivos: OK"  
echo "✅ Posso criar scripts: OK"
echo ""
echo "🚀 Pronto para criar a infraestrutura Docker!"